; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/EvanBarnesCL/Crunchlabs_DRV8835.git#2342a8cb9b350890c9354cd54e832d3ef6c2a415
	https://github.com/guru-florida/PWMFreak.git#0.2.0
	sensorium/Mozzi@2.0.4
	robtillaart/AS5600@0.6.7
	mike-matera/FastPID@1.3.1
build_flags = 
	-std=gnu++17
	-Iinclude
build_unflags = -std=gnu++11
